[package]
name = "hayai-playout-core"
version = "0.1.0"
edition = "2021"

[dependencies]
gstreamer = { workspace = true }
glib = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = "3.10"