[package]
name = "hayai-playout-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
glib = "0.21.1"
gstreamer = "0.24.0"
gstreamer-pbutils = "=0.24.0"

[dev-dependencies]
tempfile = "3.21.0"
